spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/tinkoff_hw8}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_by.default_null_ordering: last
        format_sql: true
    open-in-view: false
    show-sql: true
    generate-ddl: true

server:
  port: 8081

token:
  jwt:
    start-index: 7
    signing-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA53VzmIVVZZWyNm266l82
    duration-minutes: 20
  notes:
    generation-key: C18A15257292AE13A453A1F1A9818
    duration-minutes: 5
    cleanup-minutes: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.8, 0.95, 0.99
  prometheus:
    metrics:
      export:
        enabled: true